# Generated by Django 5.2.5 on 2025-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
